// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/whopper.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status request processing
type Status int32

const (
	// 200 expected behaviour
	Status_OK Status = 0
	// 500 could not process but archive error trace
	Status_ERROR Status = 1
	// 200 unexpected events occured during processing but no errors
	Status_WARNING Status = 2
	// 400 faulty invoke information provided
	Status_INVALID Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "WARNING",
		3: "INVALID",
	}
	Status_value = map[string]int32{
		"OK":      0,
		"ERROR":   1,
		"WARNING": 2,
		"INVALID": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_whopper_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_whopper_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{0}
}

type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status of the request
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// additional information about the status, like - status:"OK" status_message:"website resources have been downloaded and stored successful"
	StatusMessage string `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	// timestamp like "1972-01-01T10:00:20.021Z"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{0}
}

func (x *Head) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *Head) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Head) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Newspapers []string `protobuf:"bytes,2,rep,name=newspapers,proto3" json:"newspapers,omitempty"`
}

func (x *HubRequest) Reset() {
	*x = HubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubRequest) ProtoMessage() {}

func (x *HubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubRequest.ProtoReflect.Descriptor instead.
func (*HubRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{1}
}

func (x *HubRequest) GetNewspapers() []string {
	if x != nil {
		return x.Newspapers
	}
	return nil
}

type HubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *Head `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *HubResponse) Reset() {
	*x = HubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubResponse) ProtoMessage() {}

func (x *HubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubResponse.ProtoReflect.Descriptor instead.
func (*HubResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{2}
}

func (x *HubResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

type DiscovererRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*InDiscovererInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *DiscovererRequest) Reset() {
	*x = DiscovererRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscovererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscovererRequest) ProtoMessage() {}

func (x *DiscovererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscovererRequest.ProtoReflect.Descriptor instead.
func (*DiscovererRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{3}
}

func (x *DiscovererRequest) GetInfo() []*InDiscovererInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DiscovererResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Articles []*ArticleHead `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Head     *Head          `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *DiscovererResponse) Reset() {
	*x = DiscovererResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscovererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscovererResponse) ProtoMessage() {}

func (x *DiscovererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscovererResponse.ProtoReflect.Descriptor instead.
func (*DiscovererResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{4}
}

func (x *DiscovererResponse) GetArticles() []*ArticleHead {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *DiscovererResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

// request data
type InDiscovererInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Newspaper string `protobuf:"bytes,1,opt,name=newspaper,proto3" json:"newspaper,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	LatestId  int64  `protobuf:"varint,3,opt,name=latestId,proto3" json:"latestId,omitempty"`
}

func (x *InDiscovererInfo) Reset() {
	*x = InDiscovererInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InDiscovererInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InDiscovererInfo) ProtoMessage() {}

func (x *InDiscovererInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InDiscovererInfo.ProtoReflect.Descriptor instead.
func (*InDiscovererInfo) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{5}
}

func (x *InDiscovererInfo) GetNewspaper() string {
	if x != nil {
		return x.Newspaper
	}
	return ""
}

func (x *InDiscovererInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InDiscovererInfo) GetLatestId() int64 {
	if x != nil {
		return x.LatestId
	}
	return 0
}

// response data
type OutDiscovererInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewArticleHeads []*ArticleHead `protobuf:"bytes,2,rep,name=newArticleHeads,proto3" json:"newArticleHeads,omitempty"`
}

func (x *OutDiscovererInfo) Reset() {
	*x = OutDiscovererInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutDiscovererInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutDiscovererInfo) ProtoMessage() {}

func (x *OutDiscovererInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutDiscovererInfo.ProtoReflect.Descriptor instead.
func (*OutDiscovererInfo) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{6}
}

func (x *OutDiscovererInfo) GetNewArticleHeads() []*ArticleHead {
	if x != nil {
		return x.NewArticleHeads
	}
	return nil
}

//  INFO: only the URL is needed to download resources from a website
//  the additional information, id and newspaper is used to async match the request
type DownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// request id / article id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// html website data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// response head
	Head *Head `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

type ParserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Newspaper string `protobuf:"bytes,2,opt,name=newspaper,proto3" json:"newspaper,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ParserRequest) Reset() {
	*x = ParserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserRequest) ProtoMessage() {}

func (x *ParserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserRequest.ProtoReflect.Descriptor instead.
func (*ParserRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{9}
}

func (x *ParserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParserRequest) GetNewspaper() string {
	if x != nil {
		return x.Newspaper
	}
	return ""
}

func (x *ParserRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ParserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Newspaper string `protobuf:"bytes,2,opt,name=newspaper,proto3" json:"newspaper,omitempty"`
	Text      []byte `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Head      *Head  `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *ParserResponse) Reset() {
	*x = ParserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserResponse) ProtoMessage() {}

func (x *ParserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserResponse.ProtoReflect.Descriptor instead.
func (*ParserResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{10}
}

func (x *ParserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParserResponse) GetNewspaper() string {
	if x != nil {
		return x.Newspaper
	}
	return ""
}

func (x *ParserResponse) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *ParserResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

type TranslatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TargetLanguage string `protobuf:"bytes,3,opt,name=targetLanguage,proto3" json:"targetLanguage,omitempty"`
}

func (x *TranslatorRequest) Reset() {
	*x = TranslatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorRequest) ProtoMessage() {}

func (x *TranslatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorRequest.ProtoReflect.Descriptor instead.
func (*TranslatorRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{11}
}

func (x *TranslatorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslatorRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslatorRequest) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

type TranslatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TranslatedText []byte `protobuf:"bytes,2,opt,name=translatedText,proto3" json:"translatedText,omitempty"`
	Head           *Head  `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *TranslatorResponse) Reset() {
	*x = TranslatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatorResponse) ProtoMessage() {}

func (x *TranslatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatorResponse.ProtoReflect.Descriptor instead.
func (*TranslatorResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{12}
}

func (x *TranslatorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslatorResponse) GetTranslatedText() []byte {
	if x != nil {
		return x.TranslatedText
	}
	return nil
}

func (x *TranslatorResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

type AnalyzerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AnalyzerRequest) Reset() {
	*x = AnalyzerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerRequest) ProtoMessage() {}

func (x *AnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerRequest.ProtoReflect.Descriptor instead.
func (*AnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalyzerRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Head *Head  `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *AnalyzerResponse) Reset() {
	*x = AnalyzerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerResponse) ProtoMessage() {}

func (x *AnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerResponse.ProtoReflect.Descriptor instead.
func (*AnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{14}
}

func (x *AnalyzerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalyzerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AnalyzerResponse) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

type Newspaper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the newspaper
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URLs which will be fet into the discoverer
	ArticleDiscoveryUrls []string `protobuf:"bytes,2,rep,name=articleDiscoveryUrls,proto3" json:"articleDiscoveryUrls,omitempty"`
}

func (x *Newspaper) Reset() {
	*x = Newspaper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Newspaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newspaper) ProtoMessage() {}

func (x *Newspaper) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newspaper.ProtoReflect.Descriptor instead.
func (*Newspaper) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{15}
}

func (x *Newspaper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Newspaper) GetArticleDiscoveryUrls() []string {
	if x != nil {
		return x.ArticleDiscoveryUrls
	}
	return nil
}

// Structure of an newspaper article
type Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head      *ArticleHead      `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body      *ArticleBody      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Analytics *ArticleAnalytics `protobuf:"bytes,3,opt,name=analytics,proto3" json:"analytics,omitempty"`
}

func (x *Article) Reset() {
	*x = Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{16}
}

func (x *Article) GetHead() *ArticleHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Article) GetBody() *ArticleBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Article) GetAnalytics() *ArticleAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

// General article information which is provided by the article discoverer
type ArticleHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id of the article (unique)
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// URL which leads to the article text
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// article release date
	ReleaseDate string `protobuf:"bytes,3,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	// Title of the article
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Subtitle of the article
	Subtitle string `protobuf:"bytes,5,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	// General description of the article
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Category of the article on the newspaper
	Category string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *ArticleHead) Reset() {
	*x = ArticleHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleHead) ProtoMessage() {}

func (x *ArticleHead) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleHead.ProtoReflect.Descriptor instead.
func (*ArticleHead) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{17}
}

func (x *ArticleHead) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleHead) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ArticleHead) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *ArticleHead) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleHead) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ArticleHead) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArticleHead) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// TODO: This message is used to store general article information
// This information is provided by the article parser / article translator
type ArticleBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Article text how it is written on the website
	OriginalText string `protobuf:"bytes,1,opt,name=originalText,proto3" json:"originalText,omitempty"`
	// Article text translated if the original language is not english
	TranslatedText string `protobuf:"bytes,2,opt,name=translatedText,proto3" json:"translatedText,omitempty"`
	// Tells if the article has been translated
	Articletranslated bool `protobuf:"varint,3,opt,name=articletranslated,proto3" json:"articletranslated,omitempty"`
	// Original language of the article
	OriginalLanguage string `protobuf:"bytes,4,opt,name=originalLanguage,proto3" json:"originalLanguage,omitempty"`
	// Some newspapers
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ArticleBody) Reset() {
	*x = ArticleBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleBody) ProtoMessage() {}

func (x *ArticleBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleBody.ProtoReflect.Descriptor instead.
func (*ArticleBody) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{18}
}

func (x *ArticleBody) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *ArticleBody) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *ArticleBody) GetArticletranslated() bool {
	if x != nil {
		return x.Articletranslated
	}
	return false
}

func (x *ArticleBody) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *ArticleBody) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// TODO: This message is used to store article analytics data
// This information is provided by the article analyzer
type ArticleAnalytics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ArticleAnalytics) Reset() {
	*x = ArticleAnalytics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_whopper_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleAnalytics) ProtoMessage() {}

func (x *ArticleAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_api_whopper_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleAnalytics.ProtoReflect.Descriptor instead.
func (*ArticleAnalytics) Descriptor() ([]byte, []int) {
	return file_api_whopper_proto_rawDescGZIP(), []int{19}
}

func (x *ArticleAnalytics) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_whopper_proto protoreflect.FileDescriptor

var file_api_whopper_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x68, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x1f, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x2c, 0x0a, 0x0a, 0x48, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73, 0x22, 0x28, 0x0a,
	0x0b, 0x48, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x22, 0x3a, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x6e, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x59, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x22, 0x5e,
	0x0a, 0x10, 0x49, 0x6e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x11, 0x4f, 0x75, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x0f, 0x6e, 0x65, 0x77, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x0f, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x22, 0x51, 0x0a, 0x10, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x22, 0x4f, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x6d, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x73, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x22, 0x5f, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x22, 0x67, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x22, 0x35, 0x0a,
	0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x51, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x22, 0x53, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x73, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x7e, 0x0a, 0x07,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2f, 0x0a, 0x09, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x09, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x22, 0xc1, 0x01, 0x0a,
	0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2c, 0x0a, 0x11,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0x35, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x03, 0x32, 0x2c, 0x0a, 0x03, 0x48, 0x75, 0x62,
	0x12, 0x25, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x48, 0x75, 0x62, 0x12, 0x0b, 0x2e, 0x48, 0x75, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x48, 0x75, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x43, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x12, 0x12, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x3f, 0x0a, 0x0a,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x34, 0x0a,
	0x06, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x12, 0x0e, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x32, 0x44, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x36, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x3c, 0x0a, 0x08, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x07, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65,
	0x12, 0x10, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x6f, 0x6e, 0x61, 0x72, 0x64, 0x70, 0x61, 0x68,
	0x6c, 0x6b, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x77, 0x68, 0x6f, 0x70, 0x70,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_whopper_proto_rawDescOnce sync.Once
	file_api_whopper_proto_rawDescData = file_api_whopper_proto_rawDesc
)

func file_api_whopper_proto_rawDescGZIP() []byte {
	file_api_whopper_proto_rawDescOnce.Do(func() {
		file_api_whopper_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_whopper_proto_rawDescData)
	})
	return file_api_whopper_proto_rawDescData
}

var file_api_whopper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_whopper_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_whopper_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: Status
	(*Head)(nil),                  // 1: Head
	(*HubRequest)(nil),            // 2: HubRequest
	(*HubResponse)(nil),           // 3: HubResponse
	(*DiscovererRequest)(nil),     // 4: DiscovererRequest
	(*DiscovererResponse)(nil),    // 5: DiscovererResponse
	(*InDiscovererInfo)(nil),      // 6: InDiscovererInfo
	(*OutDiscovererInfo)(nil),     // 7: OutDiscovererInfo
	(*DownloadRequest)(nil),       // 8: DownloadRequest
	(*DownloadResponse)(nil),      // 9: DownloadResponse
	(*ParserRequest)(nil),         // 10: ParserRequest
	(*ParserResponse)(nil),        // 11: ParserResponse
	(*TranslatorRequest)(nil),     // 12: TranslatorRequest
	(*TranslatorResponse)(nil),    // 13: TranslatorResponse
	(*AnalyzerRequest)(nil),       // 14: AnalyzerRequest
	(*AnalyzerResponse)(nil),      // 15: AnalyzerResponse
	(*Newspaper)(nil),             // 16: Newspaper
	(*Article)(nil),               // 17: Article
	(*ArticleHead)(nil),           // 18: ArticleHead
	(*ArticleBody)(nil),           // 19: ArticleBody
	(*ArticleAnalytics)(nil),      // 20: ArticleAnalytics
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_api_whopper_proto_depIdxs = []int32{
	0,  // 0: Head.status:type_name -> Status
	21, // 1: Head.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: HubResponse.head:type_name -> Head
	6,  // 3: DiscovererRequest.info:type_name -> InDiscovererInfo
	18, // 4: DiscovererResponse.articles:type_name -> ArticleHead
	1,  // 5: DiscovererResponse.head:type_name -> Head
	18, // 6: OutDiscovererInfo.newArticleHeads:type_name -> ArticleHead
	1,  // 7: DownloadResponse.head:type_name -> Head
	1,  // 8: ParserResponse.head:type_name -> Head
	1,  // 9: TranslatorResponse.head:type_name -> Head
	1,  // 10: AnalyzerResponse.head:type_name -> Head
	18, // 11: Article.head:type_name -> ArticleHead
	19, // 12: Article.body:type_name -> ArticleBody
	20, // 13: Article.analytics:type_name -> ArticleAnalytics
	2,  // 14: Hub.RunHub:input_type -> HubRequest
	4,  // 15: Discoverer.Discover:input_type -> DiscovererRequest
	8,  // 16: Downloader.Download:input_type -> DownloadRequest
	10, // 17: Parser.Parse:input_type -> ParserRequest
	12, // 18: Translator.Translate:input_type -> TranslatorRequest
	14, // 19: Analyzer.Analyze:input_type -> AnalyzerRequest
	3,  // 20: Hub.RunHub:output_type -> HubResponse
	5,  // 21: Discoverer.Discover:output_type -> DiscovererResponse
	9,  // 22: Downloader.Download:output_type -> DownloadResponse
	11, // 23: Parser.Parse:output_type -> ParserResponse
	13, // 24: Translator.Translate:output_type -> TranslatorResponse
	15, // 25: Analyzer.Analyze:output_type -> AnalyzerResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_whopper_proto_init() }
func file_api_whopper_proto_init() {
	if File_api_whopper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_whopper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscovererRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscovererResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InDiscovererInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutDiscovererInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Newspaper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_whopper_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleAnalytics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_whopper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_api_whopper_proto_goTypes,
		DependencyIndexes: file_api_whopper_proto_depIdxs,
		EnumInfos:         file_api_whopper_proto_enumTypes,
		MessageInfos:      file_api_whopper_proto_msgTypes,
	}.Build()
	File_api_whopper_proto = out.File
	file_api_whopper_proto_rawDesc = nil
	file_api_whopper_proto_goTypes = nil
	file_api_whopper_proto_depIdxs = nil
}
